### ISSUE TITLE
Text too light on light background

### ISSUE THREAD

**Issue by victormihalache** [rigormorrtiss/discordo#563]
I'm one of those people that use light theme during the day, even for the terminal. Discordo doesn't account for it:

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/6ab31d55-4da4-426e-a7b4-d1111e647767" />

**Comment by ayn2op** [comment]
How are you setting the background color? I am using Ghostty with builtin themes:

GruvboxLight:
<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/7984cfd8-7d4e-4c7a-894c-3cf43713a28a" />

Monokai Pro Light:
<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/a4a546a7-14e9-49ec-92d8-85c06a109c17" />

**Comment by victormihalache** [comment]
I am not setting anything. It’s the default macOS terminal

**Comment by ayn2op** [comment]
~~Does e97e697a03dcc61acf2dc36a246e47593640b43b fix your issue?~~ Update: 519d0276c31e2c71b330239eaee0390425c15708 should fix the issue.

<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/32d1ddd5-3d96-43a2-a2a8-36bd2ab55a4d" />

**Comment by victormihalache** [comment]
That does fix it, thank you!

**Comment by victormihalache** [comment]
It doesn't fix when selecting

https://github.com/user-attachments/assets/a96030ec-32e2-4cc8-8c08-e346fe044947
