### ISSUE TITLE
Hash check failed on Scoop

### ISSUE THREAD

**Issue by maxstellar** [rigormorrtiss/discordo#579]
```Installing 'discordo' (1.0) [64bit] from 'vvxrtues' bucket
discordo_Windows_X64.zip (5.0 MB) [=============================================================================] 100%
Checking hash of discordo_Windows_X64.zip ... ERROR Hash check failed!
App:         vvxrtues/discordo
URL:         https://nightly.link/ayn2op/discordo/workflows/ci/main/discordo_Windows_X64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    9fa9a77d93b192b8ae92e01f1f9a8b46c1a2d72ef159b2e439ea04f6b16c6eca
Actual:      ef8b302ba595262f9dcb8c55566dec9d3ca286c3579cf619b192ea951e289a07

**Comment by HeadHunter4621** [comment]
I also have this issue, I hope it gets fixed soon
```Installing 'discordo' (1.0) [64bit] from 'vvxrtues' bucket
discordo_Windows_X64.zip (5.0 MB) [===========================================================================] 100%
Checking hash of discordo_Windows_X64.zip ... ERROR Hash check failed!
App:         vvxrtues/discordo
URL:         https://nightly.link/ayn2op/discordo/workflows/ci/main/discordo_Windows_X64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    03f155c7ac4b6550654177f8d97b381bab19226d46e9e238c06b6c73da699ba4
Actual:      0dae3df655268c297321c9c773eb35ac0548c01f3e5ed5255f99255c0ce64987

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/vvirtues/bucket/issues/new?title=discordo%401.0%3a+hash+check+failed

**Comment by Emberyo** [comment]
same issue

```
Installing 'discordo' (1.0) [64bit] from 'vvxrtues' bucket
discordo_Windows_X64.zip (5.1 MB) [===========================================================================] 100%
Checking hash of discordo_Windows_X64.zip ... ERROR Hash check failed!
App:         vvxrtues/discordo
URL:         https://nightly.link/ayn2op/discordo/workflows/ci/main/discordo_Windows_X64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    ad752ba0ef2fa461d2a696e97062d4885f7a99106efec54d7fc9f6580f9e8e40
Actual:      4357353b0c521acabeb7c95201a3b07aae031d940b8fccebc87504d462056bee

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/vvirtues/bucket/issues/new?title=discordo%401.0%3a+hash+check+failed
```

**Comment by ayn2op** [comment]
@vvirtues

**Comment by ypurpl** [comment]
ill take a look at it

**Comment by ypurpl** [comment]
fixed for now, not sure why its acting like this but let me know again if this happens
the actions build seems to be working fine so it must be an issue with timing

**Comment by Emberyo** [comment]
this is not fixed for me may be because im using a admin powershell window

```
 Get-FileHash : The file 'C:\Users\Ember Church\scoop\apps\discordo\1.0\discordo_Windows_X64.zip' cannot be read: Operation did not complete successfully
because the file contains a virus or potentially unwanted software.
At C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:634 char:16
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\Users\Ember ...Windows_X64.zip:PSObject) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FileReadError,Get-FileHash

You cannot call a method on a null-valued expression.
At C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:634 char:5
+     $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Content : Operation did not complete successfully because the file contains a virus or potentially unwanted software.
At C:\Users\Emberyo\scoop\apps\scoop\current\lib\core.ps1:1379 char:16
+         return Get-Content $file -Encoding byte -TotalCount 8
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\Users\Ember ...Windows_X64.zip:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand

ERROR Hash check failed!
App:         vvxrtues/discordo
URL:         https://nightly.link/ayn2op/discordo/workflows/ci/main/discordo_Windows_X64.zip
First bytes:
Expected:    ad752ba0ef2fa461d2a696e97062d4885f7a99106efec54d7fc9f6580f9e8e40
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/vvirtues/bucket/issues/new?title=discordo%401.0%3a+hash+check+failed
``` 

edit: happens on a admin command prompt as well

**Comment by ypurpl** [comment]
run `scoop update`

**Comment by ypurpl** [comment]
actually it seems the file is getting flagged for malware
but you still need to update anyway because scoop is still looking for the old hash

**Comment by Emberyo** [comment]
i forgor about updating stuff

**Comment by Emberyo** [comment]
has lines that might help you
```
Copy-Item: C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:95
Line |
  95 |              Copy-Item $cached $to
     |              ~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\Emberyo\scoop\cache\discordo#1.0#536580d.zip'.
Checking hash of discordo_Windows_X64.zip ... Get-FileHash: C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:634
Line |
 634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\Emberyo\scoop\apps\discordo\1.0\discordo_Windows_X64.zip' because it does not exist.
InvalidOperation: C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:634
Line |
 634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
ERROR Hash check failed!
App:         vvxrtues/discordo
URL:         https://nightly.link/ayn2op/discordo/workflows/ci/main/discordo_Windows_X64.zip
Expected:    4357353b0c521acabeb7c95201a3b07aae031d940b8fccebc87504d462056bee
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/vvirtues/bucket/issues/new?title=discordo%401.0%3a+hash+check+failed
```

**Comment by ypurpl** [comment]
> ```
> Copy-Item: C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:95
> Line |
>   95 |              Copy-Item $cached $to
>      |              ~~~~~~~~~~~~~~~~~~~~~
>      | Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\Emberyo\scoop\cache\discordo#1.0#536580d.zip'.
> Checking hash of discordo_Windows_X64.zip ... Get-FileHash: C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:634
> Line |
>  634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
>      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot find path 'C:\Users\Emberyo\scoop\apps\discordo\1.0\discordo_Windows_X64.zip' because it does not exist.
> InvalidOperation: C:\Users\Emberyo\scoop\apps\scoop\current\lib\install.ps1:634
> Line |
>  634 |      $actual = (Get-FileHash -Path $file -Algorithm $algorithm).Hash.T …
>      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | You cannot call a method on a null-valued expression.
> ERROR Hash check failed!
> App:         vvxrtues/discordo
> URL:         https://nightly.link/ayn2op/discordo/workflows/ci/main/discordo_Windows_X64.zip
> Expected:    4357353b0c521acabeb7c95201a3b07aae031d940b8fccebc87504d462056bee
> Actual:
> ```

still being detected as a virus, cannot do anything about that aside from temporarily disabling defender or whatever you use

**Comment by Emberyo** [comment]
added C: as an excluded folder and disabled everyinth i remeber to disable i hate windbows

**Comment by Emberyo** [comment]
disable everything and add your drive you are on as an excluded folder if disabling everything you see doesnt work it should install then
enable everything back after and or add the discordo folder as an excluded folder
```
Checking hash of discordo_Windows_X64.zip ... ok.
Extracting discordo_Windows_X64.zip ... done.
Linking ~\scoop\apps\discordo\current => ~\scoop\apps\discordo\1.0
Creating shim for 'discordo'.
'discordo' (1.0) was installed successfully!

``` 

edit: thanks
